# Matrix

In [2]:
import numpy as np

In [3]:
# Basic matrix
A = np.array([[1, 2, 3],
             [4, 5, 6]])

print(A.shape) # (2, 3)
print(A.ndim)  # 2
print(A[0, 1]) # 2 <- row 0, col 1

(2, 3)
2
2


In [4]:
# Identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Zero matrix
Z = np.zeros((3, 4))
print(Z.shape)
print(Z)

(3, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Ones matrix
O = np.ones((2, 3))
print(O)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Diagonal matrix
D = np.diag([5, 3, 7])
print(D)

[[5 0 0]
 [0 3 0]
 [0 0 7]]


#### Dataset as matrix

In [10]:
# Mercari dataset simulation
# 5 products x 4 features
# [prices, conditions, shipping, category]

X = np.array([
    [299, 3, 0, 12],
    [149, 1, 60, 5],
    [999, 4, 0, 8],
    [49, 2, 30, 3],
    [599, 5, 0, 15]
])


print("Shape:", X.shape)
print("Product 1:", X[0]) # row 0
print("All prices:", X[:, 0]) # col 0

Shape: (5, 4)
Product 1: [299   3   0  12]
All prices: [299 149 999  49 599]


In [11]:
# Check symmetric matrix
A = np.array([[4, 2, 1],
              [2, 5, 3],
              [1, 3, 6]])

is_symmetric = np.array_equal(A, A.T)
print(is_symmetric) # True

True
