In [2]:
import numpy as np

In [3]:
# Scalar -> only a number
a = 5
b = 3.14

learning_rate = 0.01

print(f"Scalers: {a, b, learning_rate}")

Scalers: (5, 3.14, 0.01)


In [4]:
# Create Vectors
v = np.array([3, 5, 4])

# Mercari product vector

product = np.array([299.0, 3, 0, 12])

print(v) # [3, 5, 4]
print(v.shape) # (2, ) <- 2D vector
print(product.shape) # (4, ) <- 4D vector

[3 5 4]
(3,)
(4,)


In [5]:
# Vector Properties
v = np.array([3, 5])


print(v.ndim) # 1 -> 1D array
print(v.shape) # (2, ) -> 2 elements
print(v.dtype) # int64 -> data type
print(len(v))  # 2 -> length

1
(2,)
int64
2


In [6]:
##### Column vs Row Vector #####


# Row vector -> shape (1, 3)
row = np.array([1, 2, 3])


# Column vector -> (3, 1)
col = np.array([[1], [2], [3]])


# Transpose: row -> column
v = np.array([1, 2, 3])

print(v.T) # same (in 1D transpose remain same)
print(row.T.shape) # (3, 1) -> become a column

[1 2 3]
(3,)


In [7]:
# Basic Vector OPS
a = np.array([3, 5])
b = np.array([1, 2])

print(a+b) # [4 7] -> addition
print(a-b) # [2 3] -> subtraction
print(3*a) # [9 15] -> scalar multiply
print(np.dot(a, b)) # 13 -> dot product

[4 7]
[2 3]
[ 9 15]
13


### Vector Operations

In [9]:
# vector addition & subtraction
a = np.array([3, 5])
b = np.array([1, 2])

print(a+b)
print(a-b)

# Word embedding 
king = np.array([0.8, 0.3, 0.1])
man = np.array([0.7, 0.1, 0.0])
woman = np.array([0.2, 0.9, 0.0])

queen_approx = king - man + woman
print(f"Queen_approx: {queen_approx}")

[4 7]
[2 3]
Queen_approx: [0.3 1.1 0.1]


In [10]:
# Scalar Multipication
weights = np.array([0.5, 0.3, 0.8])
gradient = np.array([0.1, 0.4, 0.2])
lr = 0.01

# Gradient descent update step 
new_weight = weights - lr * gradient
print(new_weight)

[0.499 0.296 0.798]


In [12]:
# Dot Product (Important)

a = np.array([3, 4])
b = np.array([2, 1])

# method 1 
print(np.dot(a, b)) # 10

# method 2
print(a @ b) # 10 <- prefer this


# Neural network neuron simulation
inputs = np.array([1.0, 2.0, 3.0])
weights = np.array([0.2, 0.5, 0.1])
bias = 0.3

output = inputs @ weights + bias
print(output)

10
10
1.8


In [13]:
# Magnitude (norm)

v = np.array([3, 4])

# Method 1 - manual
mag = np.sqrt(np.sum(v**2))
print(mag) # 5.0


# Method 2 - numpy linalg
print(np.linalg.norm(v)) # 5.0 <- prefer this

5.0
5.0


In [15]:
# cosine similarity (from scratch)

def cosine_similarity(a, b):
    dot = np.dot(a, b)
    mag_a = np.linalg.norm(a)
    mag_b = np.linalg.norm(b)

    return dot / (mag_a * mag_b)


user = np.array([5, 3, 0, 1])
movieA = np.array([4, 3, 1, 0])
movieB = np.array([1, 0, 5, 4])

print(cosine_similarity(user, movieA))  # 0.96 <- similar!
print(cosine_similarity(user, movieB))  # 0.23 <- not similar

0.9613406389911041
0.2347382389307855
